PS2_MOUSE_ENABLE = yes
PS2_ENABLE = yes
PS2_DRIVER = usart
AUDIO_ENABLE = yes


OS_DETECTION_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
MOUSE_KEYS = yes
COMMAND_ENABLE = no

EXTRAFLAGS+=-flto
