PS2_MOUSE_ENABLE = yes
PS2_ENABLE = yes
PS2_DRIVER = usart

AUDIO_ENABLE = no
MUSIC_ENABLE = no


OS_DETECTION_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
MOUSE_KEYS = yes
COMMAND_ENABLE = no

LEADER_ENABLE = no

EXTRAFLAGS+=-flto
KEY_OVERRIDE_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
