#PS2_MOUSE_ENABLE = no
#PS2_ENABLE = no
#PS2_DRIVER = usart

AUDIO_ENABLE = no
MUSIC_ENABLE = no


OS_DETECTION_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
MOUSE_KEYS = yes
COMMAND_ENABLE = no

LEADER_ENABLE = no

EXTRAFLAGS+=-flto
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
# MAGIC_ENABLE = no
